package com.fintrack.analytics;

import static org.assertj.core.api.Assertions.assertThat;

import com.fintrack.reference.ReferenceData;
import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/**
 * The Java habit summary must match @ft/core's habitSummary() exactly. The
 * fixture (inputs + the TypeScript output) is generated by
 * `npm run export:backend-data`; a core test keeps it in sync.
 */
class HabitSummaryGoldenTest {
    private static final JsonMapper JSON = JsonMapper.builder().build();

    @Test
    void matchesTheTypeScriptImplementation() throws IOException {
        JsonNode g;
        try (InputStream in = getClass().getResourceAsStream("/golden/habit-summary.json")) {
            g = JSON.readTree(in);
        }
        Map<String, Double> rates = new HashMap<>();
        g.get("rates").properties().forEach(e -> rates.put(e.getKey(), e.getValue().doubleValue()));
        HabitSummary.Converter fx = (amount, from, to) -> from.equals(to) ? amount : (amount / rates.get(from)) * rates.get(to);
        String base = g.get("baseCurrency").stringValue();

        List<HabitSummary.Tx> txs = new ArrayList<>();
        for (JsonNode t : g.get("transactions")) {
            String note = t.get("note").isNull() ? null : t.get("note").stringValue();
            txs.add(new HabitSummary.Tx(t.get("date").stringValue(), t.get("kind").stringValue(),
                    fx.convert(t.get("amount").doubleValue(), t.get("currency").stringValue(), base), t.get("categoryName").stringValue(), note));
        }
        List<HabitSummary.AccountIn> accounts = new ArrayList<>();
        for (JsonNode a : g.get("accounts")) {
            accounts.add(new HabitSummary.AccountIn(a.get("type").stringValue(), a.get("currency").stringValue(), a.get("balance").doubleValue(), a.get("archived").booleanValue()));
        }
        List<HabitSummary.GoalIn> goals = new ArrayList<>();
        for (JsonNode x : g.get("goals")) {
            goals.add(new HabitSummary.GoalIn(x.get("name").stringValue(), x.get("targetAmount").doubleValue(), x.get("saved").doubleValue(),
                    x.get("currency").stringValue(), x.get("deadline").isNull() ? null : x.get("deadline").stringValue(), !x.get("completedAt").isNull()));
        }
        ReferenceData ref = new ReferenceData(JSON);
        HabitSummary.Summary actual = HabitSummary.compute(txs, accounts, goals, base, LocalDate.parse(g.get("today").stringValue()), ref::isDiscretionary, fx);

        JsonNode expected = g.get("expected");
        JsonNode got = JSON.valueToTree(actual);
        assertThat(expected.get("recurringMonthlyCosts").doubleValue()).as("fixture exercises recurring bills").isPositive();
        assertSame("", expected, got);
    }

    /** Structural equality; numbers compared as doubles (2500 equals 2500.0). */
    private static void assertSame(String path, JsonNode expected, JsonNode actual) {
        if (expected.isNumber()) {
            assertThat(actual.isNumber()).as(path).isTrue();
            assertThat(actual.doubleValue()).as(path).isEqualTo(expected.doubleValue());
        } else if (expected.isObject()) {
            assertThat(actual.propertyNames()).as(path).containsExactlyInAnyOrderElementsOf(expected.propertyNames());
            expected.properties().forEach(e -> assertSame(path + "." + e.getKey(), e.getValue(), actual.get(e.getKey())));
        } else if (expected.isArray()) {
            assertThat(actual.size()).as(path).isEqualTo(expected.size());
            for (int i = 0; i < expected.size(); i++) assertSame(path + "[" + i + "]", expected.get(i), actual.get(i));
        } else {
            assertThat(actual).as(path).isEqualTo(expected);
        }
    }

    @Test
    void emptyHistoryAnalysesNothing() {
        HabitSummary.Summary s = HabitSummary.compute(List.of(), List.of(), List.of(), "RON", LocalDate.of(2026, 10, 15), c -> false, (a, f, t) -> a);
        assertThat(s.monthsAnalyzed()).isZero();
        assertThat(s.savingsRate()).isZero();
        assertThat(s.emergencyFundMonths()).isZero();
        assertThat(s.topExpenseCategories()).isEmpty();
    }
}
